### ISSUE TITLE
Content does not appear on page load, but does on window resize

### ISSUE THREAD

**Issue by scifri** [INN/pym-shortcode#11]
I'm using pym for a quiz that gets it's content from a Google Sheet. When I load the page, nothing appears. In the inspector, I can see pym is showing up, but the height is 0. If I resize the window in any way, it starts working and the quiz appears. 

Here's the page I'm referring to: http://www.sciencefriday.com/segments/quiz/ 
And the page pym is drawing from: http://scifri.github.io/newsquiz/index.html

I'm guessing this bug could be coming from one of the javascript files this quiz is using, which include jquery.js, tabletop.js, and script.js. Not sure if there's a documented problem with using pym with one of these.

The quiz code is from the Mother Jones open source quiz tool: https://github.com/motherjones/newsquiz

**Comment by benlk** [comment]
@scifri Was this closed because you eventually got it to work, or for another reason?

**Comment by scifri** [comment]
@benlk I went through INN's repos after I posted this and found the mother jones news quiz wrapper, which solved the problem!
