### ISSUE TITLE
How will we deal with a breaking change in Pym?

### ISSUE THREAD

**Issue by benlk** [INN/pym-shortcode#15]
Eventually, Pym.js may publish a backwards-incompatible API change, at which point we'll need to figure out how to handle existing graphics embedded with a version of this shortcode that does not specify to use the older version of pym. (https://github.com/nprapps/pym.js/tree/master#versioning)

How should we handle that breaking change?

**Comment by rclachance** [comment]
we'll cross that bridge when we get there (but hopefully we won't ever have to)
