### ISSUE TITLE
Override pym_id to resize after following links in iframe?

### ISSUE THREAD

**Issue by KatieMFritz** [INN/pym-shortcode#20]
I'm so glad you've created this plugin! 😁 

I have some clients who want to use it to embed event registration and membership forms from another application. To work well, the iframe needs to resize at each screen of the process. 

The [Pym docs](http://blog.apps.npr.org/pym.js/#examples) show how to do this (jump to `Example: Resizing after following links in the iframe`), and I've tried to follow the instructions. I am using a local WordPress test site and the following code on each page of my [silly little child site](http://spooky-trains.surge.sh/):

```html
    <script src="https://pym.nprapps.org/pym.v1.min.js"></script>
    <script>
      var pymChild = new pym.Child({ id: '[UNIQUE ID FOR EACH PAGE]' })
    </script>
```

(I've also tried replacing `id` with `pym_id` - no effect that I can see.)

The iframe loads beautifully for the first page, but when I click through to other pages inside the iframe, the iframe height doesn't change.  **The ID of the parent div is always `pym_0`, where I would expect it to be replaced with my specific unique ID from the child page.**

Any tips? I don't mind forking the plugin and making my own changes, but if there's a way I can make it work with the existing code, that would be best for my clients.

Thanks!

**Comment by benlk** [comment]
From my understanding of http://blog.apps.npr.org/pym.js/api/pym.js/1.2.0/module-pym.Child.html, the `id` in every `pymChild` configuration should be `pym_0` for this embed. The `id` parameter is supposed to *match* the ID on the parent page, not set it. The ID of the parent doesn't change, so the ID on every child page needs to be set to match the parent. In http://blog.apps.npr.org/pym.js/#example-follow-links, both of the child pages have and `id` match the ID of the parent iframe.

I'm not sure if there's a way to automatically set the ID of the child to match the ID of the parent element; perhaps you could do this with a small Javascript script and a query parameter `?pym_id=example` that is applied to the first child page loaded. The JavaScript would check for the presence of that query parameter, and if it is set, add that query parameter to all the links in the child page. When the link is clicked, the new child page would have the query parameter, so the JavaScript on the new child page would set it as well.

We should probably make a new `pym_id` parameter on the shortcode that allows end users to configure the ID of the generated embed on the page, but I don't think that's going to fix your problem in this ticket.

**Comment by benlk** [comment]
@KatieMFritz the next version of the Pym Shortcode will include an `id=""` attribute that will allow you to set a custom ID on the iframe, to solve this problem: https://github.com/INN/pym-shortcode/pull/25
