### ISSUE TITLE
Allow passing a class name to target DIV

### ISSUE THREAD

**Issue by eyeseast** [INN/pym-shortcode#23]
We have a couple size-based class names in our site styles, and it's been handy to use those to size embeds. When we're just writing HTML, it's easy to do something like:

```html
<div class="interactive medium" data-pym-src="..."></div>
```

Would be great to be able to:

```
[pym src="..." class="interactive medium"]
```

**Comment by benlk** [comment]
Resolved with #27. Thanks for the suggestion!
