### ISSUE TITLE
This plugin needs a logo for its wp.org listing.

### ISSUE THREAD

**Issue by benlk** [INN/pym-shortcode#43]
Nothing fancy, but still, needs a logo.

https://wordpress.org/plugins/pym-shortcode/

https://developer.wordpress.org/plugins/wordpress-org/plugin-assets/#plugin-icons

**Comment by benlk** [comment]
Right now, we're using the analytics dashicon for the shortcode: https://developer.wordpress.org/resource/dashicons/#analytics

<img width="429" alt="screen shot 2018-09-10 at 11 01 42 am" src="https://user-images.githubusercontent.com/1754187/45305769-08a1c800-b4e9-11e8-89f1-ab720c42b5eb.png">

**Comment by benlk** [comment]
@alykat does NPR have any logos you use for pym.js? Or is the text at the top of http://blog.apps.npr.org/pym.js/ pretty much it?
<img width="291" alt="screen shot 2018-09-10 at 11 03 34 am" src="https://user-images.githubusercontent.com/1754187/45305864-3a1a9380-b4e9-11e8-8e04-ea1daf81fac9.png">

**Comment by alykat** [comment]
There's no logo for pym.js. The type that's there was just from the template we used, not a special choice to brand the library.

**Comment by tylermachado** [comment]
Points of clarification:

1. Do we need the 3D-ish icon with colorful background, [a la the ones we have here](https://labs.inn.org/tools/), _and also_ a smaller one-color icon for the block selection seen in @benlk's screenshot above?

2. Does the existing `< / >` type icon work, as seen on https://labs.inn.org/tools/ ?

**Comment by benlk** [comment]
1. Smaller one-color icon for the block selection is not necessary
2. Yes.

**Comment by benlk** [comment]
Oh, neat, those icons are SVGs. I'll add https://labs.inn.org/wp-content/themes/labs/images/plugins/pym-shortcode.svg as `icon.svg` in the assets svn dir, following https://developer.wordpress.org/plugins/wordpress-org/plugin-assets/#plugin-icons

**Comment by benlk** [comment]
It's live: https://wordpress.org/plugins/pym-shortcode/
