### ISSUE TITLE
Gutenberg Block failing for me on Wordpress.com

### ISSUE THREAD

**Issue by eads** [INN/pym-shortcode#56]
Without warning, this plugin stopped working on WP.com today. The Pym JS library doesn't load. Support has asked me to contact yall (what up INN friends!!). If you have any ideas, I'd love to know. I don't see any updates to the plugin recently, and it had been working for weeks up until now.

I did have a notion that Gutenberg might be a culprit, but the same problem crops up in the classic editor. We have a business account, so we can use unfiltered html in the advanced editor, and that works fine.

**Comment by eads** [comment]
Scratch the classic editor issue. The shortcode works.

**Comment by benlk** [comment]
Whoa, wp.com allows the Pym.js Embeds plugin to be used on their platform? I did not know that, and am pleasantly surprised.

Can you provide:
- an example post where it's failing to work, and the `post_content` of that post
- a screenshot of the plugin's settings page, or the settings values it's using
- your Gutenberg and WordPress versions

Thanks for the bug report!

**Comment by benlk** [comment]
Wordpress 4.9.8
Gutenberg 4.1
PHP 7.0:

> Parse error: syntax error, unexpected T_STRING, expecting T_CONSTANT_ENCAPSED_STRING or '(' in /home/rsholin/webapps/wp/wp-content/plugins/pym-shortcode/inc/shortcode.php on line 8

But only in posts, not on the homepage?

https://github.com/INN/pym-shortcode/blob/a06f10bd701551352654a546b3fb3b9b7892a491/inc/shortcode.php#L8

**Comment by benlk** [comment]
https://github.com/WordPress/gutenberg/releases/tag/v4.1.1 

It was Gutenberg; Version 4.1 broke dynamic blocks, and Pym.js Embeds' block is a dynamic block.
